services:
  browserless:
    container_name: 'browserless'
    image: browserless/chrome:latest
    env_file: '.browserless.env'
    ports:
      - '8000:8000'
    restart: always
  bot:
    container_name: 'bot'
    build: .
    env_file: '.env'
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - browserless
    links:
      - 'browserless:browserless'
